# Generated by Django 4.2.21 on 2025-05-20 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HypotekaWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('krok', models.PositiveSmallIntegerField(choices=[(1, 'Jméno klienta'), (2, 'Co chce klient financovat'), (3, 'Návrh financování'), (4, 'Výběr banky'), (5, 'Příprava žádosti'), (6, 'Kompletace podkladů'), (7, 'Podání žádosti'), (8, 'Odhad'), (9, 'Schvalování'), (10, 'Příprava úvěrové dokumentace'), (11, 'Podpis úvěrové dokumentace'), (12, 'Příprava čerpání'), (13, 'Čerpání'), (14, 'Zahájení splácení'), (15, 'Podmínky pro vyčerpání')])),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('poznamka', models.TextField(blank=True)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflowy', to='klienti.klient')),
            ],
            options={
                'verbose_name': 'Krok workflow hypotéky',
                'verbose_name_plural': 'Kroky workflow hypotéky',
                'ordering': ['krok', 'datum'],
            },
        ),
    ]
