# Generated by Django 4.2.21 on 2025-05-20 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('klienti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='datum',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
