# Generated by Django 4.2.21 on 2025-05-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klienti', '0002_klient_datum'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='cerpani',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='klient',
            name='co_financuje',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='klient',
            name='deadline_cerpani',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='deadline_co_financuje',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='deadline_kompletace_podkladu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='deadline_navrh_financovani',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='deadline_odhad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='deadline_podani_zadosti',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='deadline_podminky_pro_splaceni',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='deadline_podpis_uverove_dokumentace',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='deadline_priprava_cerpani',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='deadline_priprava_uverove_dokumentace',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='deadline_priprava_zadosti',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='deadline_schvalovani',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='deadline_vyber_banky',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='deadline_zahajeni_splaceni',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='kompletace_podkladu',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='klient',
            name='navrh_financovani',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='klient',
            name='odhad',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='klient',
            name='podani_zadosti',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='klient',
            name='podminky_pro_splaceni',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='klient',
            name='podpis_uverove_dokumentace',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='klient',
            name='priprava_cerpani',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='klient',
            name='priprava_uverove_dokumentace',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='klient',
            name='priprava_zadosti',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='klient',
            name='schvalovani',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='klient',
            name='vyber_banky',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='klient',
            name='zahajeni_splaceni',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
