# Generated by Django 4.2.21 on 2025-05-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klienti', '0003_klient_cerpani_klient_co_financuje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='splneno_cerpani',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='splneno_co_financuje',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='splneno_kompletace_podkladu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='splneno_navrh_financovani',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='splneno_odhad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='splneno_podani_zadosti',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='splneno_podminky_pro_splaceni',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='splneno_podpis_uverove_dokumentace',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='splneno_priprava_cerpani',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='splneno_priprava_uverove_dokumentace',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='splneno_priprava_zadosti',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='splneno_schvalovani',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='splneno_vyber_banky',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='splneno_zahajeni_splaceni',
            field=models.DateField(blank=True, null=True),
        ),
    ]
