# Generated by Django 4.2.21 on 2025-05-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klienti', '0004_klient_splneno_cerpani_klient_splneno_co_financuje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='cena',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
