# Generated by Django 4.2.21 on 2025-05-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klienti', '0005_klient_cena'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='navrh_financovani_procento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Návrh financování v %'),
        ),
    ]
