# Generated by Django 4.2.21 on 2025-05-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klienti', '0006_klient_navrh_financovani_procento'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='navrh_financovani_castka',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Návrh financování částka'),
        ),
    ]
