# Generated by Django 4.2.21 on 2025-05-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klienti', '0007_klient_navrh_financovani_castka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='cerpani',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='kompletace_podkladu',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='odhad',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='podani_zadosti',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='podminky_pro_splaceni',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='podpis_uverove_dokumentace',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='priprava_cerpani',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='priprava_uverove_dokumentace',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='priprava_zadosti',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='schvalovani',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='zahajeni_splaceni',
            field=models.TextField(blank=True),
        ),
    ]
