# Generated by Django 4.2.21 on 2025-05-22 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klienti', '0008_alter_klient_cerpani_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zmena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popis', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zmeny', to='klienti.klient')),
            ],
        ),
        migrations.CreateModel(
            name='Poznamka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poznamky', to='klienti.klient')),
            ],
        ),
    ]
