# Generated by Django 4.2.21 on 2025-05-22 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('klienti', '0009_zmena_poznamka'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Uživatel (klient), který má přístup ke svému záznamu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='klient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('poradce', 'Finanční poradce'), ('klient', 'Klient')], default='klient', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
