# Generated by Django 4.2.21 on 2025-05-22 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('klienti', '0010_klient_user_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Uživatel (klient), který má přístup ke svému záznamu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='klienti', to=settings.AUTH_USER_MODEL),
        ),
    ]
