# Generated by Django 4.2.21 on 2025-05-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klienti', '0011_alter_klient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='duvod_zamitnuti',
            field=models.CharField(blank=True, help_text='Vyplňte pouze v případě zamítnuté hypotéky', max_length=255, null=True, verbose_name='Důvod zamítnutí'),
        ),
    ]
