# Generated by Django 4.2.21 on 2025-05-23 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klienti', '0012_klient_duvod_zamitnuti'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifikaceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prijemce', models.EmailField(max_length=254)),
                ('typ', models.CharField(choices=[('deadline', 'Blížící se deadline'), ('stav', 'Změna stavu'), ('zamítnutí', 'Zamítnutí hypotéky')], max_length=30)),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('obsah', models.TextField(blank=True)),
                ('uspesne', models.BooleanField(default=True)),
                ('klient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='klienti.klient')),
            ],
        ),
    ]
