# Generated by Django 4.2.21 on 2025-05-26 19:00

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('klienti', '0013_notifikacelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='cerpani',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='co_financuje',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='duvod_zamitnuti',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Vyplňte pouze v případě zamítnuté hypotéky', null=True, verbose_name='Důvod zamítnutí'),
        ),
        migrations.AlterField(
            model_name='klient',
            name='jmeno',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='klient',
            name='kompletace_podkladu',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='odhad',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='podani_zadosti',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='podminky_pro_splaceni',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='podpis_uverove_dokumentace',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='priprava_cerpani',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='priprava_uverove_dokumentace',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='priprava_zadosti',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='schvalovani',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='zahajeni_splaceni',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='poznamka',
            name='text',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='zmena',
            name='popis',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
    ]
