# Generated by Django 4.2.21 on 2025-06-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klienti', '0014_alter_klient_cerpani_alter_klient_co_financuje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='jmeno_index',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
