# Generated by Django 4.2.21 on 2025-11-21 20:11

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("klienti", "0015_klient_jmeno_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="klient",
            name="cerpani",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="klient",
            name="kompletace_podkladu",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="klient",
            name="odhad",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="klient",
            name="podani_zadosti",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="klient",
            name="podminky_pro_splaceni",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="klient",
            name="podpis_uverove_dokumentace",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="klient",
            name="priprava_cerpani",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="klient",
            name="priprava_uverove_dokumentace",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="klient",
            name="priprava_zadosti",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="klient",
            name="schvalovani",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="klient",
            name="zahajeni_splaceni",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, default=""
            ),
        ),
    ]
