# Generated by Django 4.2.21 on 2025-11-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klienti", "0016_alter_klient_cerpani_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="klient",
            name="vlastni_zdroj",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Vlastní zdroj",
            ),
        ),
    ]
