# Generated by Django 4.2.21 on 2025-11-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klienti", "0017_klient_vlastni_zdroj"),
    ]

    operations = [
        migrations.AddField(
            model_name="klient",
            name="deadline_schvalene_financovani",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="klient",
            name="schvalena_hypoetka_castka",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Schválená výše hypotéky",
            ),
        ),
        migrations.AddField(
            model_name="klient",
            name="schvalene_cena",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Schválená cena",
            ),
        ),
        migrations.AddField(
            model_name="klient",
            name="schvalene_financovani",
            field=models.CharField(
                blank=True,
                help_text="Schválené parametry hypotéky po schválení",
                max_length=255,
                verbose_name="Schválené financování",
            ),
        ),
        migrations.AddField(
            model_name="klient",
            name="schvaleny_ltv_procento",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Schválené LTV (%)",
            ),
        ),
        migrations.AddField(
            model_name="klient",
            name="schvaleny_vlastni_zdroj",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Schválený vlastní zdroj",
            ),
        ),
        migrations.AddField(
            model_name="klient",
            name="splneno_schvalene_financovani",
            field=models.DateField(blank=True, null=True),
        ),
    ]
