# Generated by Django 4.2.21 on 2025-11-21 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("klienti", "0018_klient_deadline_schvalene_financovani_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="klient",
            name="schvalene_cena",
        ),
    ]
