# Generated by Django 4.2.21 on 2026-01-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("klienti", "0020_update_workflow_choices"),
    ]

    operations = [
        migrations.RenameField(
            model_name="klient",
            old_name="schvalena_hypoetka_castka",
            new_name="schvalena_hypoteka_castka",
        ),
    ]
