# Generated by Django 4.2.21 on 2026-01-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klienti", "0021_rename_hypoetka_to_hypoteka"),
    ]

    operations = [
        migrations.AddField(
            model_name="klient",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="E-mailová adresa pro odeslání přihlašovacích údajů",
                max_length=255,
                verbose_name="E-mail klienta",
            ),
        ),
    ]
