# GitHub Actions workflow pro automatizované testování Django aplikace
# Spustí se při každém pushi a pull requestu na libovolnou větev

name: Django CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_hypoteky
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      DJANGO_SETTINGS_MODULE: hypoteky.settings
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: test_hypoteky
    steps:
      - name: Checkout kód
        uses: actions/checkout@v4
      - name: Nastav Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Nainstaluj závislosti
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Počkej na MySQL
        run: |
          sudo apt-get install -y mysql-client
          until mysqladmin ping -h 127.0.0.1 -uroot -proot --silent; do sleep 2; done
      - name: Spusť testy
        run: |
          python manage.py test
